replicaCount: 1

image:
  repository: yonatan009/flask-aws-monitor
  tag: "0.1.0"
  pullPolicy: IfNotPresent

# Requires ConfigMap "aws-config" in the target namespace
# with keys: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION

service:
  port: 5001
  targetPort: 5001

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: flask.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

readinessProbe:
  tcpSocket:
    port: 5001
  initialDelaySeconds: 10
  periodSeconds: 5

livenessProbe:
  tcpSocket:
    port: 5001
  initialDelaySeconds: 20
  periodSeconds: 10

